import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
    createDb() {
    const questions = [
        {
            "question_id": 1,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "You consistently deliver working, tested software every 30 days or less.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 2,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Each release is driven by business need.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 3,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Each Sprint you are continuously improving.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 4,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Team is having fun and there is a high energy level..",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 5,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Team presents their own work during Sprint Review.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 6,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Overtime is rare and happens voluntarily.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 7,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Discussing, criticizing and experimenting with the process is welcome.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 8,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "There is a clearly defined Product Owner role.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 9,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Product Owner is empowered to prioritize the product backlog.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 10,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Product Owner has direct contact with customer.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 11,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Product Owner is actively involved throughout each sprint.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 12,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Product Owner has direct contact with the team.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 13,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "There is a clearly defined Scrum Master role.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 14,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team works off of a Sprint backlog.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 15,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Sprint backlog is visible to any stakeholder.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 16,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team updates the Sprint Backlog daily.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 17,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Stakeholders attend the Sprint Review.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 18,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Team Members raise impediments at the Daily Scrum.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 19,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Definition of Done is met for every completed User Story when applicable.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 20,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team actively participates in the Sprint Retrospective.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 21,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Backlog grooming occurs every Sprint.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 22,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The estimates in the product backlog are given by the Team.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 23,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The output of the Sprint Planning meeting is a realistic Sprint backlog that the Team agrees is doable.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 24,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Estimates are given in relative size (e.g. Story Points) rather than hours.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 25,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "A Sprint planning meeting occurs every Sprint.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 26,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Sprints are not interrupted by unplanned work outside of the Sprint Backlog.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 27,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team usually delivers what they commit to on the Sprint Backlog.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 28,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team's historical Velocity is used for Sprint Planning.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 29,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Scrum Masters are seen as servant leaders, not managers.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 30,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team consistently answers the 3 questions.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 31,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Each team has a Definition of Done.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 32,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Only completed Stories are presented at the Sprint Review.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 33,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Everyone stands up at the Daily Scrum.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 34,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Retrospectives are held after every Sprint.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 35,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Many of the improvements identified in the retrospective are implemented in the next Sprint.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 36,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Product Owner maintains a product backlog at least one Sprint ahead of the Team.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 37,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The whole team and the Product Owner attend the Sprint Planning meeting.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 38,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Each Sprint is no longer than 30 days.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 39,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Each Sprint for a project is the same length.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 40,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team sits together during the Sprint.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 41,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team size is between 3 and 9 people.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 42,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team generally has all the skills required by the project.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 43,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team members are able to step outside their role and be cross-functional.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 44,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Acceptance tests are written in advance of development for most User Stories.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 45,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Product Owner writes the acceptance tests.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 46,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Team can modify the Sprint backlog during the Sprint to meet the Sprint Goal.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 47,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The team tracks work remaining during the Sprint using a tool like Burndown Charts.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 48,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Dependent Teams integrate during each Sprint.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 49,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Scrum Master is empowered to remove impediments for the Team.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 50,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Daily Scrum happens every day at the same time and place.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 51,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "All Team members participate in the Daily Scrum.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 52,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Daily Scrum is limited to 15 minutes.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 53,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "A Sprint Review happens every Sprint.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 54,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Feedback is encouraged and captured at the Sprint Review.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 55,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Automated unit testing is implemented where appropriate.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 56,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Automated regression testing is implemented where appropriate.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 57,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "The Sprint Backlog and/or Burndown Charts are updated daily.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 58,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Scrum artifacts (Backlogs and Burndown Charts) are visible to all project stakeholders.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 59,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Dependent Teams (a team working on the same project as other teams) are meeting together weekly to manage dependencies, e.g. Scrum of Scrums or similar.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 60,
            "survey_id": 1,
            "question_type_id": 1,
            "parameter_id": 1,
            "question": "Dependent Teams have a “chief” Product Owner or similar role who is empowered to make product decisions across all product teams.",
            "option_1": "Yes",
            "option_2": "No",
            "option_3": null,
            "option_4": null,
            "option_5": null,
            "survey_start_date": "2019-12-02T12:30:00",
            "survey_end_date": "2019-12-05T23:59:00",
            "is_active": 1,
            "survey_type_id": 1,
            "organizer_id": 1,
            "survey_type": "Agile Maturity"
        },
        {
            "question_id": 61,
            "survey_id": 3,
            "question_type_id": 3,
            "parameter_id": 1,
            "question": "I am enthusiastic about the work that I do for the team.",
            "option_1": "1",
            "option_2": "2",
            "option_3": "3",
            "option_4": "4",
            "option_5": "5",
            "survey_start_date": "2019-12-08T10:00:00",
            "survey_end_date": "2019-12-10T15:00:00",
            "is_active": 1,
            "survey_type_id": 2,
            "organizer_id": 1,
            "survey_type": "Sprint Retro Team Morale"
        },
        {
            "question_id": 62,
            "survey_id": 3,
            "question_type_id": 3,
            "parameter_id": 1,
            "question": "I find the work that I do for my team of meaning and purpose.",
            "option_1": "1",
            "option_2": "2",
            "option_3": "3",
            "option_4": "4",
            "option_5": "5",
            "survey_start_date": "2019-12-08T10:00:00",
            "survey_end_date": "2019-12-10T15:00:00",
            "is_active": 1,
            "survey_type_id": 2,
            "organizer_id": 1,
            "survey_type": "Sprint Retro Team Morale"
        },
        {
            "question_id": 63,
            "survey_id": 3,
            "question_type_id": 3,
            "parameter_id": 1,
            "question": "I am proud of the work that I do for my team",
            "option_1": "1",
            "option_2": "2",
            "option_3": "3",
            "option_4": "4",
            "option_5": "5",
            "survey_start_date": "2019-12-08T10:00:00",
            "survey_end_date": "2019-12-10T15:00:00",
            "is_active": 1,
            "survey_type_id": 2,
            "organizer_id": 1,
            "survey_type": "Sprint Retro Team Morale"
        },
        {
            "question_id": 64,
            "survey_id": 3,
            "question_type_id": 3,
            "parameter_id": 1,
            "question": "To me, the work that I do for my team is challenging.",
            "option_1": "1",
            "option_2": "2",
            "option_3": "3",
            "option_4": "4",
            "option_5": "5",
            "survey_start_date": "2019-12-08T10:00:00",
            "survey_end_date": "2019-12-10T15:00:00",
            "is_active": 1,
            "survey_type_id": 2,
            "organizer_id": 1,
            "survey_type": "Sprint Retro Team Morale"
        },
        {
            "question_id": 65,
            "survey_id": 3,
            "question_type_id": 3,
            "parameter_id": 1,
            "question": "In my team, I feel bursting with energy.",
            "option_1": "1",
            "option_2": "2",
            "option_3": "3",
            "option_4": "4",
            "option_5": "5",
            "survey_start_date": "2019-12-08T10:00:00",
            "survey_end_date": "2019-12-10T15:00:00",
            "is_active": 1,
            "survey_type_id": 2,
            "organizer_id": 1,
            "survey_type": "Sprint Retro Team Morale"
        },
        {
            "question_id": 66,
            "survey_id": 3,
            "question_type_id": 3,
            "parameter_id": 1,
            "question": "In my team, I feel fit and strong.",
            "option_1": "1",
            "option_2": "2",
            "option_3": "3",
            "option_4": "4",
            "option_5": "5",
            "survey_start_date": "2019-12-08T10:00:00",
            "survey_end_date": "2019-12-10T15:00:00",
            "is_active": 1,
            "survey_type_id": 2,
            "organizer_id": 1,
            "survey_type": "Sprint Retro Team Morale"
        },
        {
            "question_id": 67,
            "survey_id": 3,
            "question_type_id": 3,
            "parameter_id": 1,
            "question": "In my team, I quickly recover from setbacks.",
            "option_1": "1",
            "option_2": "2",
            "option_3": "3",
            "option_4": "4",
            "option_5": "5",
            "survey_start_date": "2019-12-08T10:00:00",
            "survey_end_date": "2019-12-10T15:00:00",
            "is_active": 1,
            "survey_type_id": 2,
            "organizer_id": 1,
            "survey_type": "Sprint Retro Team Morale"
        },
        {
            "question_id": 68,
            "survey_id": 3,
            "question_type_id": 3,
            "parameter_id": 1,
            "question": "In my team, I can keep going for a long time.",
            "option_1": "1",
            "option_2": "2",
            "option_3": "3",
            "option_4": "4",
            "option_5": "5",
            "survey_start_date": "2019-12-08T10:00:00",
            "survey_end_date": "2019-12-10T15:00:00",
            "is_active": 1,
            "survey_type_id": 2,
            "organizer_id": 1,
            "survey_type": "Sprint Retro Team Morale"
        }
    ]
    
    const chartData = [
        {
        "Ad-hoc Agile": 10,
        "Doing Agile": 20,
        "Being Agile": 15,
        "Thinking Agile": 15,
        "Culturally Agile": 40
        },
       {
        "Ad-hoc Agile": 10,
        "Doing Agile": 20,
        "Being Agile": 15,
        "Thinking Agile": 15,
        "Culturally Agile": 40
        },
        {
        "Ad-hoc Agile": 10,
        "Doing Agile": 20,
        "Being Agile": 15,
        "Thinking Agile": 15,
        "Culturally Agile": 40
        },
        {
        "Ad-hoc Agile": 10,
        "Doing Agile": 20,
        "Being Agile": 15,
        "Thinking Agile": 15,
        "Culturally Agile": 40
        }
    ]
    return {questions, chartData};
  }

  constructor() { }

}
